# example values

indexing-settings:
  siteConfigs:
#    - url: https://sendel.ru
#      name: sendel.ru
#    - url: https://www.lenta.ru
#      name: Лента.ру
#    - url: https://www.skillbox.ru
#      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru

server:
  port: 8080
spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/search_engine_db?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    hikari:
      schema: search_engine_schema
      connection-timeout: 10000
  jpa:
    properties:
#      dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        default_schema: public
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    url: jdbc:postgresql://localhost:5432/search_engine_db
    user: postgres
    password: postgres