# example values

indexing-settings:
  siteConfigs:
    - url: https://sendel.ru
      name: sendel.ru
#    - url: https://www.lenta.ru
#      name: Лента.ру
#    - url: https://www.skillbox.ru
#      name: Skillbox
#    - url: https://www.playback.ru
#      name: PlayBack.Ru

server:
  port: 8080
spring:
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/search_engine_db?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    hikari:
      schema: search_engine_schema
      connection-timeout: 10000
  jpa:
    properties:
#      dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        jdbc:
          batch_size: 500
        default_schema: public
        order_inserts: true
        order_updates: true
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    url: jdbc:postgresql://localhost:5432/search_engine_db
    user: postgres
    password: postgres

logging:
  level:
    org.springframework.transaction: DEBUG
    org.hibernate.transaction: DEBUG

app:
  cache:
    cache-names:
      - lemmaCache
    caches:
      lemmaCache:
        expire: 10m