# example values

indexing-settings:
  siteConfigs:
    - url: https://sendel.ru
      name: sendel.ru
#    - url: https://www.lenta.ru
#      name: Лента.ру
#    - url: https://www.skillbox.ru
#      name: Skillbox
#    - url: https://www.playback.ru
#      name: PlayBack.Ru

server:
  port: 8080
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true